
services:
  reverse_proxy:
    container_name: testapp_proxy
    image: nginx
    depends_on:
      - testapp
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/logs/:/var/log/nginx/
    command: [nginx, '-g', 'daemon off;']
    environment:
      WITH_PROXY: 'True'
