version: '3.7'

services:
  testapp:
    build:
      context: .
      target: app
    image: testapp
    container_name: testapp
    command: bash -c "gunicorn -k uvicorn.workers.UvicornWorker -w ${WORKERS} -b 0.0.0.0:8000 main:app"
    depends_on:
      - database
    restart: on-failure
    volumes:
      - ./src/:/app/src/
    environment:
      ENVIRONMENT: prod
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      DEBUG: 'False'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_DB: '${POSTGRES_DB}'
      WORKERS: '${WORKERS:-1}'
    ports:
      - 8000:8000

  database:
    image: postgres:13.4-alpine
    container_name: postgres
    volumes:
      - ./data/postgres/:/var/lib/postgresql/
    restart: on-failure
    environment:
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_DB: '${POSTGRES_DB}'
    ports:
      - 5432:5432

